version: '3.9'
services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knut4
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/knut4?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
  gpt4all:
    image: ghcr.io/nomic-ai/gpt4all:latest
    command: ["/bin/sh","-c","echo 'Placeholder GPT4All container'; sleep 3600"]
volumes:
  db_data:
