version: '3.8'
services:
  backend:
    build:
      context: ./backend
    image: knut4-backend:latest
    container_name: knut4-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build:
      context: ./frontend
    image: knut4-frontend:latest
    container_name: knut4-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
