# Copy this file to application-secret.yml and fill secrets. Do NOT commit the real file.
app:
  jwt:
    secret: REPLACE_WITH_BASE64_SECRET
naver:
  api:
    client-id: YOUR_NAVER_CLIENT_ID
    client-secret: YOUR_NAVER_CLIENT_SECRET
