spring:
  application:
    name: backend1
  profiles:
    active: dev
  
  # OpenAPI Documentation
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

# Logging
logging:
  level:
    com.knut4.backend1: INFO
    org.springframework.security: DEBUG

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  # H2 Database for development
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console

---
# Test Profile  
spring:
  config:
    activate:
      on-profile: test
  
  # H2 Database for testing
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  # MySQL Database for production
  datasource:
    url: jdbc:mysql://localhost:3306/knut4_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:knut4_user}
    password: ${DB_PASSWORD:}
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect