app:
  jwt:
    secret: CHANGE_ME_MIN_64_BYTES_LENGTH_BASE64
    issuer: knut4
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 1209600
naver:
  client-id: dymynnfqap
  client-secret: bA1Rnok8h9Od5iVbapFMWMCjYx4ftP3Fi56aoyRk
