app:
  jwt:
    secret: CHANGE_ME_MIN_64_BYTES_LENGTH_BASE64
    issuer: knut4
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 1209600
naver:
  map:
    client-id: YOUR_NAVER_CLIENT_ID
    client-secret: YOUR_NAVER_CLIENT_SECRET
    base-url: https://openapi.naver.com/v1/search/local.json
